#!/usr/bin/env bash

set -euo pipefail

LOGGER_TAG="wiretap"

usage() {
    echo "Usage: $0 <add|remove> <interface> <span-port>" >&2
    exit 2
}

if ! command -v ip > /dev/null 2>&1
then
    echo "Missing depandancy: ip"
    exit 1
fi

if ! command -v tc > /dev/null 2>&1
then
    echo "Missing depandancy: tc "
    exit 1
fi

[[ $# -eq 2 || $# -eq 3 ]] || usage

action="$1"
interface="$2"

if [[ $# -eq 3 ]]; then
    span="$3"
fi


case "$action" in
    add|remove)
        ;;
    *)
        echo "Invalid action: $action" >&2
        usage
        ;;
esac


add_tap() {

    if [[ -z "$interface" || -z "$span" ]]; then
        usage
    fi

    if ! ip link show dev "$interface" >/dev/null 2>&1; then
        echo "Error: source interface '$interface' does not exist." >&2
        exit 1
    fi

    if ! ip link show dev "$span" >/dev/null 2>&1; then
        echo "Error: SPAN interface '$span' does not exist." >&2
        exit 1
    fi

    if ! tc qdisc add dev "$interface" clsact; then
         echo "Error: failed to add qdisk to '$interface'." >&2
         return 1
    fi

    if ! tc filter add dev "$interface" ingress \
        protocol all \
        u32 match u8 0 0 \
        action mirred egress mirror dev "$span"
    then
        echo "Error: failed to add ingress mirror filter." >&2
        remove_tap
        return 1
    fi

    if ! tc filter add dev "$interface" egress \
        protocol all \
        u32 match u8 0 0 \
        action mirred egress mirror dev "$span"
    then
        echo "Error: failed to add egress mirror filter." >&2
        remove_tap
        return 1
    fi

    echo "Added $interface ingress and egress mirroring to $span."
}

remove_tap() {
    if [[ -z "$interface" ]]; then
        usage
    fi

    if ! ip link show dev "$interface" >/dev/null 2>&1; then
        echo "Error: source interface '$interface' does not exist." >&2
        exit 1
    fi

    tc qdisc del dev "$interface" clsact

    echo "Removed all ingress and egress mirroring from $interface"
}

case "$action" in
    add)
        logger -t "$LOGGER_TAG" \
            "Taping interface ($interface) to span port ($span)"
        add_tap $interface $span
        ;;
    remove)
        logger -t "$LOGGER_TAG" \
            "removing tap from interface ($interface) connected to span port ($span)"
        remove_tap
        ;;
esac